In [1]:
import pandas as pd
from sqlalchemy import create_engine
import numpy as np

# Oscars Dataframe Work

In [2]:
oscars_df = pd.read_csv("../Data/BigML_Dataset_5f50a62c2fb31c516d000176.csv")
oscars_df

,year,movie,movie_id,certificate,duration,genre,rate,metascore,synopsis,votes,...,New_York_Film_Critics_Circle_nominated,New_York_Film_Critics_Circle_nominated_categories,Los_Angeles_Film_Critics_Association_won,Los_Angeles_Film_Critics_Association_won_categories,Los_Angeles_Film_Critics_Association_nominated,Los_Angeles_Film_Critics_Association_nominated_categories,release_date.year,release_date.month,release_date.day-of-month,release_date.day-of-week
0,2001,Kate & Leopold,tt0035423,PG-13,118,Comedy|Fantasy|Romance,6.4,44.0,An English Duke from 1876 is inadvertedly drag...,66660,...,0,NaN,0,NaN,0,NaN,2001.0,12.0,25.0,2.0
1,2000,Chicken Run,tt0120630,G,84,Animation|Adventure|Comedy,7.0,88.0,When a cockerel apparently flies into a chicke...,144475,...,1,Best Animated Film,1,Best Animation,1,Best Animation,2000.0,6.0,23.0,5.0
2,2005,Fantastic Four,tt0120667,PG-13,106,Action|Adventure|Family,5.7,40.0,A group of astronauts gain superpowers after a...,273203,...,0,NaN,0,NaN,0,NaN,2005.0,7.0,8.0,5.0
3,2002,Frida,tt0120679,R,123,Biography|Drama|Romance,7.4,61.0,"A biography of artist Frida Kahlo, who channel...",63852,...,0,NaN,0,NaN,0,NaN,2002.0,11.0,22.0,5.0
4,2001,The Lord of the Rings: The Fellowship of the Ring,tt0120737,PG-13,178,Adventure|Drama|Fantasy,8.8,92.0,A meek Hobbit from the Shire and eight compani...,1286275,...,0,NaN,1,Best Music,2,Best Music|Best Production Design,2001.0,12.0,19.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1178,2017,Call Me by Your Name,tt5726616,R,132,Drama|Romance,8.3,93.0,"In Northern Italy in 1983, seventeen year-old ...",38170,...,1,Best Actor,3,Best Actor|Best Director|Best Picture,3,Best Actor|Best Director|Best Picture,NaN,NaN,NaN,NaN
1179,2017,Phantom Thread,tt5776858,R,130,Drama|Romance,8.4,90.0,"Set in 1950's London, Reynolds Woodcock is a r...",7380,...,1,Best Screenplay,1,Best Music,1,Best Music,NaN,NaN,NaN,NaN
1180,2017,Victoria & Abdul,tt5816682,PG-13,111,Biography|Drama|History,6.8,58.0,Queen Victoria strikes up an unlikely friendsh...,12888,...,0,NaN,0,NaN,0,NaN,2017.0,10.0,6.0,5.0
1181,2017,"Roman J. Israel, Esq.",tt6000478,PG-13,122,Crime|Drama,6.3,58.0,"Roman J. Israel, Esq., a driven, idealistic de...",3205,...,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
1182,2017,The Post,tt6294822,PG-13,116,Biography|Drama|History,7.4,83.0,A cover-up that spanned four U.S. Presidents p...,21292,...,0,NaN,0,NaN,0,NaN,2018.0,1.0,12.0,5.0

In [3]:
for col in oscars_df.columns: 
    print(col)

year
movie
movie_id
certificate
duration
genre
rate
metascore
synopsis
votes
gross
release_date
user_reviews
critic_reviews
popularity
awards_wins
awards_nominations
Oscar_Best_Picture_won
Oscar_Best_Picture_nominated
Oscar_Best_Director_won
Oscar_Best_Director_nominated
Oscar_Best_Actor_won
Oscar_Best_Actor_nominated
Oscar_Best_Actress_won
Oscar_Best_Actress_nominated
Oscar_Best_Supporting_Actor_won
Oscar_Best_Supporting_Actor_nominated
Oscar_Best_Supporting_Actress_won
Oscar_Best_Supporting_Actress_nominated
Oscar_Best_AdaScreen_won
Oscar_Best_AdaScreen_nominated
Oscar_Best_OriScreen_won
Oscar_Best_OriScreen_nominated
Oscar_nominated
Oscar_nominated_categories
Golden_Globes_won
Golden_Globes_won_categories
Golden_Globes_nominated
Golden_Globes_nominated_categories
BAFTA_won
BAFTA_won_categories
BAFTA_nominated
BAFTA_nominated_categories
Screen_Actors_Guild_won
Screen_Actors_Guild_won_categories
Screen_Actors_Guild_nominated
Screen_Actors_Guild_nominated_categories
Critics_Choice_won
Critics_Choice_won_categories
Critics_Choice_nominated
Critics_Choice_nominated_categories
Directors_Guild_won
Directors_Guild_won_categories
Directors_Guild_nominated
Directors_Guild_nominated_categories
Producers_Guild_won
Producers_Guild_won_categories
Producers_Guild_nominated
Producers_Guild_nominated_categories
Art_Directors_Guild_won
Art_Directors_Guild_won_categories
Art_Directors_Guild_nominated
Art_Directors_Guild_nominated_categories
Writers_Guild_won
Writers_Guild_won_categories
Writers_Guild_nominated
Writers_Guild_nominated_categories
Costume_Designers_Guild_won
Costume_Designers_Guild_won_categories
Costume_Designers_Guild_nominated
Costume_Designers_Guild_nominated_categories
Online_Film_Television_Association_won
Online_Film_Television_Association_won_categories
Online_Film_Television_Association_nominated
Online_Film_Television_Association_nominated_categories
Online_Film_Critics_Society_won
Online_Film_Critics_Society_won_categories
Online_Film_Critics_Society_nominated
Online_Film_Critics_Society_nominated_categories
People_Choice_won
People_Choice_won_categories
People_Choice_nominated
People_Choice_nominated_categories
London_Critics_Circle_Film_won
London_Critics_Circle_Film_won_categories
London_Critics_Circle_Film_nominated
London_Critics_Circle_Film_nominated_categories
American_Cinema_Editors_won
American_Cinema_Editors_won_categories
American_Cinema_Editors_nominated
American_Cinema_Editors_nominated_categories
Hollywood_Film_won
Hollywood_Film_won_categories
Hollywood_Film_nominated
Hollywood_Film_nominated_categories
Austin_Film_Critics_Association_won
Austin_Film_Critics_Association_won_categories
Austin_Film_Critics_Association_nominated
Austin_Film_Critics_Association_nominated_categories
Denver_Film_Critics_Society_won
Denver_Film_Critics_Society_won_categories
Denver_Film_Critics_Society_nominated
Denver_Film_Critics_Society_nominated_categories
Boston_Society_of_Film_Critics_won
Boston_Society_of_Film_Critics_won_categories
Boston_Society_of_Film_Critics_nominated
Boston_Society_of_Film_Critics_nominated_categories
New_York_Film_Critics_Circle_won
New_York_Film_Critics_Circle_won_categories
New_York_Film_Critics_Circle_nominated
New_York_Film_Critics_Circle_nominated_categories
Los_Angeles_Film_Critics_Association_won
Los_Angeles_Film_Critics_Association_won_categories
Los_Angeles_Film_Critics_Association_nominated
Los_Angeles_Film_Critics_Association_nominated_categories
release_date.year
release_date.month
release_date.day-of-month
release_date.day-of-week

In [4]:
copied_oscars_df = oscars_df.drop(oscars_df.filter(regex='nominated').columns, axis=1)
copied_oscars_df

,year,movie,movie_id,certificate,duration,genre,rate,metascore,synopsis,votes,...,Boston_Society_of_Film_Critics_won,Boston_Society_of_Film_Critics_won_categories,New_York_Film_Critics_Circle_won,New_York_Film_Critics_Circle_won_categories,Los_Angeles_Film_Critics_Association_won,Los_Angeles_Film_Critics_Association_won_categories,release_date.year,release_date.month,release_date.day-of-month,release_date.day-of-week
0,2001,Kate & Leopold,tt0035423,PG-13,118,Comedy|Fantasy|Romance,6.4,44.0,An English Duke from 1876 is inadvertedly drag...,66660,...,0,NaN,0,NaN,0,NaN,2001.0,12.0,25.0,2.0
1,2000,Chicken Run,tt0120630,G,84,Animation|Adventure|Comedy,7.0,88.0,When a cockerel apparently flies into a chicke...,144475,...,0,NaN,1,Best Animated Film,1,Best Animation,2000.0,6.0,23.0,5.0
2,2005,Fantastic Four,tt0120667,PG-13,106,Action|Adventure|Family,5.7,40.0,A group of astronauts gain superpowers after a...,273203,...,0,NaN,0,NaN,0,NaN,2005.0,7.0,8.0,5.0
3,2002,Frida,tt0120679,R,123,Biography|Drama|Romance,7.4,61.0,"A biography of artist Frida Kahlo, who channel...",63852,...,0,NaN,0,NaN,0,NaN,2002.0,11.0,22.0,5.0
4,2001,The Lord of the Rings: The Fellowship of the Ring,tt0120737,PG-13,178,Adventure|Drama|Fantasy,8.8,92.0,A meek Hobbit from the Shire and eight compani...,1286275,...,0,NaN,0,NaN,1,Best Music,2001.0,12.0,19.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1178,2017,Call Me by Your Name,tt5726616,R,132,Drama|Romance,8.3,93.0,"In Northern Italy in 1983, seventeen year-old ...",38170,...,0,NaN,1,Best Actor,3,Best Actor|Best Director|Best Picture,NaN,NaN,NaN,NaN
1179,2017,Phantom Thread,tt5776858,R,130,Drama|Romance,8.4,90.0,"Set in 1950's London, Reynolds Woodcock is a r...",7380,...,4,Best Film|Best Director|Best Original Score|Be...,1,Best Screenplay,1,Best Music,NaN,NaN,NaN,NaN
1180,2017,Victoria & Abdul,tt5816682,PG-13,111,Biography|Drama|History,6.8,58.0,Queen Victoria strikes up an unlikely friendsh...,12888,...,0,NaN,0,NaN,0,NaN,2017.0,10.0,6.0,5.0
1181,2017,"Roman J. Israel, Esq.",tt6000478,PG-13,122,Crime|Drama,6.3,58.0,"Roman J. Israel, Esq., a driven, idealistic de...",3205,...,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
1182,2017,The Post,tt6294822,PG-13,116,Biography|Drama|History,7.4,83.0,A cover-up that spanned four U.S. Presidents p...,21292,...,0,NaN,0,NaN,0,NaN,2018.0,1.0,12.0,5.0

In [5]:
dropped_oscars=copied_oscars_df.drop(['movie_id', 'release_date.day-of-month', 'release_date.day-of-week', 'release_date.year'], axis=1)
dropped_oscars

,year,movie,certificate,duration,genre,rate,metascore,synopsis,votes,gross,...,Austin_Film_Critics_Association_won_categories,Denver_Film_Critics_Society_won,Denver_Film_Critics_Society_won_categories,Boston_Society_of_Film_Critics_won,Boston_Society_of_Film_Critics_won_categories,New_York_Film_Critics_Circle_won,New_York_Film_Critics_Circle_won_categories,Los_Angeles_Film_Critics_Association_won,Los_Angeles_Film_Critics_Association_won_categories,release_date.month
0,2001,Kate & Leopold,PG-13,118,Comedy|Fantasy|Romance,6.4,44.0,An English Duke from 1876 is inadvertedly drag...,66660,47100000.0,...,NaN,0,NaN,0,NaN,0,NaN,0,NaN,12.0
1,2000,Chicken Run,G,84,Animation|Adventure|Comedy,7.0,88.0,When a cockerel apparently flies into a chicke...,144475,106790000.0,...,NaN,0,NaN,0,NaN,1,Best Animated Film,1,Best Animation,6.0
2,2005,Fantastic Four,PG-13,106,Action|Adventure|Family,5.7,40.0,A group of astronauts gain superpowers after a...,273203,154700000.0,...,NaN,0,NaN,0,NaN,0,NaN,0,NaN,7.0
3,2002,Frida,R,123,Biography|Drama|Romance,7.4,61.0,"A biography of artist Frida Kahlo, who channel...",63852,25780000.0,...,NaN,0,NaN,0,NaN,0,NaN,0,NaN,11.0
4,2001,The Lord of the Rings: The Fellowship of the Ring,PG-13,178,Adventure|Drama|Fantasy,8.8,92.0,A meek Hobbit from the Shire and eight compani...,1286275,313840000.0,...,NaN,0,NaN,0,NaN,0,NaN,1,Best Music,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1178,2017,Call Me by Your Name,R,132,Drama|Romance,8.3,93.0,"In Northern Italy in 1983, seventeen year-old ...",38170,11300000.0,...,Best Actor|Best Adapted Screenplay|Breakthroug...,1,Best Adapted Screenplay,0,NaN,1,Best Actor,3,Best Actor|Best Director|Best Picture,NaN
1179,2017,Phantom Thread,R,130,Drama|Romance,8.4,90.0,"Set in 1950's London, Reynolds Woodcock is a r...",7380,10710000.0,...,NaN,0,NaN,4,Best Film|Best Director|Best Original Score|Be...,1,Best Screenplay,1,Best Music,NaN
1180,2017,Victoria & Abdul,PG-13,111,Biography|Drama|History,6.8,58.0,Queen Victoria strikes up an unlikely friendsh...,12888,22250000.0,...,NaN,0,NaN,0,NaN,0,NaN,0,NaN,10.0
1181,2017,"Roman J. Israel, Esq.",PG-13,122,Crime|Drama,6.3,58.0,"Roman J. Israel, Esq., a driven, idealistic de...",3205,11940000.0,...,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN
1182,2017,The Post,PG-13,116,Biography|Drama|History,7.4,83.0,A cover-up that spanned four U.S. Presidents p...,21292,58790000.0,...,NaN,0,NaN,0,NaN,0,NaN,0,NaN,1.0

In [6]:
dropped_oscars["gross"].dtype

dtype('float64')

In [7]:
no_nans_oscars=dropped_oscars.replace(np.nan, 0)

In [8]:
cols = ['gross', 'release_date.month']
no_nans_oscars[cols] = no_nans_oscars[cols].applymap(np.int64)
no_nans_oscars.sample(5)

,year,movie,certificate,duration,genre,rate,metascore,synopsis,votes,gross,...,Austin_Film_Critics_Association_won_categories,Denver_Film_Critics_Society_won,Denver_Film_Critics_Society_won_categories,Boston_Society_of_Film_Critics_won,Boston_Society_of_Film_Critics_won_categories,New_York_Film_Critics_Circle_won,New_York_Film_Critics_Circle_won_categories,Los_Angeles_Film_Critics_Association_won,Los_Angeles_Film_Critics_Association_won_categories,release_date.month
1063,2014,Birdman or (The Unexpected Virtue of Ignorance),R,119,Comedy|Drama|Romance,7.8,88.0,Illustrated upon the progress of his latest Br...,420750,42340000,...,Best Cinematography|Best Score|Best Original S...,3,Best Cinematography|Best Original Score|Best O...,4,Best Actor|Best Supporting Actress|Best Screen...,0,0,1,Best Cinematography,11
178,2002,The Time Machine,PG-13,96,Sci-Fi|Adventure|Action,5.9,42.0,"Hoping to alter the events of the past, a 19th...",105871,56680000,...,0,0,0,0,0,0,0,0,0,3
270,2003,2 Fast 2 Furious,PG-13,107,Action|Crime|Thriller,5.9,38.0,Former cop Brian O'Conner is called upon to bu...,198288,127080000,...,0,0,0,0,0,0,0,0,0,6
89,2000,Memento,R,113,Mystery|Thriller,8.5,80.0,A man juggles searching for his wife's murdere...,879688,25530000,...,0,0,0,1,Best Screenplay,0,0,1,Best Screenplay,5
498,2006,Blood Diamond,R,143,Adventure|Drama|Thriller,8.0,64.0,"A fisherman, a smuggler, and a syndicate of bu...",413538,57370000,...,0,0,0,0,0,0,0,0,0,12

In [12]:
how_many_genres = []
cartoon= []

for index, row in no_nans_oscars.iterrows():
    if 'Animation' in row['genre']:
        cartoon.append(True)
    else:
        cartoon.append(False)
        
    number_of_genres = len(row['genre'].split("|"))
    how_many_genres.append(number_of_genres)

no_nans_oscars['cartoon'] = cartoon
no_nans_oscars['number_of_genres'] = how_many_genres
no_nans_oscars.sample(5)

,year,movie,certificate,duration,genre,rate,metascore,synopsis,votes,gross,...,Denver_Film_Critics_Society_won_categories,Boston_Society_of_Film_Critics_won,Boston_Society_of_Film_Critics_won_categories,New_York_Film_Critics_Circle_won,New_York_Film_Critics_Circle_won_categories,Los_Angeles_Film_Critics_Association_won,Los_Angeles_Film_Critics_Association_won_categories,release_date.month,cartoon,number_of_genres
1101,2015,Room,R,118,Drama,8.2,86.0,A young boy is raised within the confines of a...,199790,14680000,...,Best Actress,0,0,0,0,0,0,1,False,1
347,2008,Indiana Jones and the Kingdom of the Crystal S...,PG-13,122,Action|Adventure|Fantasy,6.2,65.0,"Famed archaeologist/adventurer Dr. Henry ""Indi...",344036,317010000,...,0,0,0,0,0,0,0,5,False,3
543,2016,"Hail, Caesar!",PG-13,106,Comedy|Mystery,6.3,72.0,A Hollywood fixer in the 1950s works to keep t...,82710,29997095,...,0,0,0,0,0,0,0,2,False,2
1178,2017,Call Me by Your Name,R,132,Drama|Romance,8.3,93.0,"In Northern Italy in 1983, seventeen year-old ...",38170,11300000,...,Best Adapted Screenplay,0,0,1,Best Actor,3,Best Actor|Best Director|Best Picture,0,False,2
808,2013,Iron Man 3,PG-13,130,Action|Adventure|Sci-Fi,7.2,62.0,When Tony Stark's world is torn apart by a for...,576005,408990000,...,0,0,0,0,0,0,0,5,False,3

In [11]:
renamed_oscars= no_nans_oscars.rename(columns={'movie':'movie_title'})

In [15]:
oscars_df_final=renamed_oscars[["year", "movie_title", "certificate", "duration", "genre", "rate", "metascore", "votes", "gross", "user_reviews", "critic_reviews", "cartoon", "number_of_genres"]].copy(
    ).reset_index(drop=True)
renamed_df
oscars_df_final.head()

,year,movie_title,certificate,duration,genre,rate,metascore,votes,gross,user_reviews,critic_reviews,cartoon,number_of_genres
0,2001,Kate & Leopold,PG-13,118,Comedy|Fantasy|Romance,6.4,44.0,66660,47100000,318.0,125.0,False,3
1,2000,Chicken Run,G,84,Animation|Adventure|Comedy,7.0,88.0,144475,106790000,361.0,186.0,True,3
2,2005,Fantastic Four,PG-13,106,Action|Adventure|Family,5.7,40.0,273203,154700000,1008.0,278.0,False,3
3,2002,Frida,R,123,Biography|Drama|Romance,7.4,61.0,63852,25780000,272.0,126.0,False,3
4,2001,The Lord of the Rings: The Fellowship of the Ring,PG-13,178,Adventure|Drama|Fantasy,8.8,92.0,1286275,313840000,5078.0,296.0,False,3

In [ ]:
oscars_df_final.to_csv("../Output/oscars_df_final.csv")

In [20]:
nominations_df=renamed_oscars[["year", "movie_title", "awards_wins", "awards_nominations", "Oscar_Best_Picture_won","Oscar_Best_Director_won","Oscar_Best_Actor_won","Oscar_Best_Actress_won","Oscar_Best_Supporting_Actor_won","Oscar_Best_Supporting_Actress_won","Oscar_Best_AdaScreen_won","Oscar_Best_OriScreen_won"]].copy(
    ).reset_index(drop=True)
nominations_df.head()

,year,movie_title,awards_wins,awards_nominations,Oscar_Best_Picture_won,Oscar_Best_Director_won,Oscar_Best_Actor_won,Oscar_Best_Actress_won,Oscar_Best_Supporting_Actor_won,Oscar_Best_Supporting_Actress_won,Oscar_Best_AdaScreen_won,Oscar_Best_OriScreen_won
0,2001,Kate & Leopold,1,4,No,No,No,No,No,No,No,No
1,2000,Chicken Run,5,11,No,No,No,No,No,No,No,No
2,2005,Fantastic Four,0,0,No,No,No,No,No,No,No,No
3,2002,Frida,2,12,No,No,No,No,No,No,No,No
4,2001,The Lord of the Rings: The Fellowship of the Ring,26,67,No,No,No,No,No,No,No,No

In [49]:
oscar_wins_df=nominations_df.replace(["Yes", "No"], [True, False])
oscar_wins_df.head()

,year,movie_title,awards_wins,awards_nominations,Oscar_Best_Picture_won,Oscar_Best_Director_won,Oscar_Best_Actor_won,Oscar_Best_Actress_won,Oscar_Best_Supporting_Actor_won,Oscar_Best_Supporting_Actress_won,Oscar_Best_AdaScreen_won,Oscar_Best_OriScreen_won
0,2001,Kate & Leopold,1,4,False,False,False,False,False,False,False,False
1,2000,Chicken Run,5,11,False,False,False,False,False,False,False,False
2,2005,Fantastic Four,0,0,False,False,False,False,False,False,False,False
3,2002,Frida,2,12,False,False,False,False,False,False,False,False
4,2001,The Lord of the Rings: The Fellowship of the Ring,26,67,False,False,False,False,False,False,False,False

In [ ]:
oscar_wins_df.to_csv("../Output/oscar_wins_df.csv")

# Wiki Dataframe Work

In [ ]:
wiki_df = pd.read_csv("../Data/wiki_movie_plots_deduped.csv")
wiki_df

In [ ]:
filtered_wiki_df = wiki_df.loc[(wiki_df["Origin/Ethnicity"]=="American")]
filtered_wiki_df

In [ ]:
filtered_wiki_df.columns = filtered_wiki_df.columns.str.replace(' ', '_').str.lower()
renamed_df=filtered_wiki_df.rename(columns={'title':'movie_title', 'origin/ethnicity':'country'}
                                  ).replace({'country': 'American'}, {'country': 'USA'})
renamed_df

In [ ]:
renamed_wiki_df = renamed_df.loc[(renamed_df["genre"]!="unknown")]

In [ ]:
duplicates = renamed_wiki_df[renamed_wiki_df.duplicated(['movie_title'])] 
duplicates

In [ ]:
unique_wiki_df=renamed_wiki_df.drop_duplicates(['movie_title'] , keep ='last') 
unique_wiki_df.shape

In [ ]:
wiki_df_final=unique_wiki_df[["release_year", "movie_title", "country", "genre", "wiki_page"]].copy(
    ).reset_index(drop=True).dropna(how='all')
wiki_df_final.sample(5)

In [ ]:
wiki_df_final['release_year'] = wiki_df_final['release_year'].apply(pd.to_numeric)

In [ ]:
wiki_df_final = wiki_df_final[(wiki_df_final.release_year > 1999)]

In [ ]:
wiki_df_final

In [ ]:
wiki_df_final.to_csv("../Output/wiki_clean.csv")

# Connect Local Database

In [ ]:
rds_connection_string = "postgres:3411@localhost:5432/ETL_project_movies_db"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [ ]:
engine.table_names()

# Load Dataframes into the Database

In [ ]:
wiki_df_final.to_sql(name='wiki_table', con=engine, if_exists='append', index=False)