In [16]:
##Imports
from sqlalchemy import create_engine
import pandas as pd
from sqlalchemy import create_engine

In [17]:
##Store CSV into DataFrame

csv_file = "../Data/Netflix_titles.csv"
netflix_df = pd.read_csv(csv_file)
netflix_df.sample(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
1636,s2335,Movie,Gaddar: the Traitor,Amitoj Mann,"Harbhajan Mann, Manpneet Grewal, Ashish Duggal...",India,1-Nov-18,2015,TV-14,126 min,"Dramas, International Movies, Thrillers",An Indian man who has become a major business ...
123,s158,Movie,A Choo,"Kevin Ko, Peter Tsi","Kai Ko, Ariel Lin, Darren Wang, Zhang Xiaolong...",Taiwan,14-Oct-20,2020,TV-14,101 min,"Action & Adventure, International Movies, Roma...",Determined to win the heart of his childhood c...
4966,s7164,Movie,Tottaa Pataaka Item Maal,Aditya Kripalani,"Shalini Vatsa, Chitrangada Chakraborty, Vinay ...",India,25-Jun-19,2018,TV-MA,107 min,"Dramas, Independent Movies, International Movies",Exasperated with living in perpetual fear for ...
1981,s2855,Movie,Hridaynath,Amar Gupte,"Jackie Shroff, Aditya Pancholi, Swarangi Mahar...",India,1-Jan-18,2012,TV-14,103 min,"Dramas, International Movies",A schoolteacher known for his good deeds and b...
767,s1030,Movie,Bollywood Calling,Nagesh Kukunoor,"Om Puri, Pat Cusick, Navin Nischol, Perizaad Z...",India,15-Apr-19,2001,TV-MA,102 min,"Comedies, Dramas, International Movies",A down-and-out Hollywood actor is utterly unpr...

In [18]:
##Read Columns

for col in netflix_df.columns: 
    print(col)

show_id
type
title
director
cast
country
date_added
release_year
rating
duration
listed_in
description

In [19]:
##Drop all non-Movies and only capture U.S, and movies 2000-2017
netflix_df = netflix_df[(netflix_df.type == "Movie") & (netflix_df.release_year > 1999) & (netflix_df.release_year < 2018)] 
netflix_df.sample(10)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
1313,s1863,Movie,Dream Big: Engineering Our World,Greg MacGillivray,Jeff Bridges,United States,1-Jul-18,2017,TV-G,42 min,Documentaries,"Narrated by Jeff Bridges, this compelling docu..."
387,s497,Movie,An Ordinary Man,Brad Silberling,"Ben Kingsley, Hera Hilmar, Peter Serafinowicz","Serbia, United States",1-Oct-20,2017,R,91 min,"Dramas, Thrillers",A war criminal in hiding begins to suspect tha...
2280,s3258,Movie,Justin Timberlake + the Tennessee Kids,Jonathan Demme,Justin Timberlake,United States,12-Oct-16,2016,TV-MA,90 min,Music & Musicals,"On the final nights of a world tour, director ..."
346,s445,Movie,Amar,Esteban Crespo,"María Pedraza, Pol Monen, Natalia Tena, Nacho ...",Spain,15-Jul-17,2017,TV-MA,104 min,"Dramas, International Movies, Romantic Movies",Young Laura and Carlos experience the intensit...
1002,s1385,Movie,Chupan Chupai,Mohsin Ali,"Ahsan Khan, Neelam Muneer, Faizan Khawaja, Ali...",Pakistan,15-Jan-19,2017,TV-14,118 min,"Comedies, International Movies","The lives of five hapless, petty criminals car..."
380,s489,Movie,An American Tail: The Treasures of Manhattan I...,Larry Latham,"Thomas Dekker, Dom DeLuise, Pat Musick, Nehemi...",United States,1-Apr-18,2000,G,79 min,Children & Family Movies,When Fievel and friends go hunting for buried ...
4754,s6855,Movie,The Search for Life in Space,Stephen Amezdroz,NaN,United States,1-Apr-18,2016,TV-G,32 min,Documentaries,To determine whether we're alone in the univer...
4998,s7215,Movie,Trespass Against Us,Adam Smith,"Michael Fassbender, Brendan Gleeson, Lyndsey M...",United Kingdom,22-Feb-19,2016,R,100 min,Dramas,A man from a criminal family yearns to break a...
2948,s4240,Movie,Motor Mitraan Di,Amitoj Mann,"Gurpreet Guggi, Happy Raikoti, Vikram Singh, S...",India,1-Oct-18,2016,TV-PG,117 min,"Comedies, International Movies",When three brothers unwittingly get entangled ...
3147,s4526,Movie,NOVA: Death Dive to Saturn,Terri Randall,Craig Sechler,United States,1-Jul-19,2017,TV-G,54 min,Documentaries,"After decades of amazing discoveries, spacecra..."

In [20]:
##Choose Columns, rename 

clean_netflix_df = netflix_df[['title', 'director', 'cast', 'release_year', 'rating', 'duration', 'listed_in', 'description']].copy()
clean_netflix_df = clean_netflix_df.rename(columns={'title': 'movie_title'})
clean_netflix_df = clean_netflix_df.drop_duplicates(subset='movie_title', keep='first')

clean_netflix_df=clean_netflix_df.drop_duplicates(['movie_title'] , keep ='first') 

clean_netflix_df = clean_netflix_df.reset_index(drop=True)

clean_netflix_df.to_csv("../Output/Netflix_clean.csv")

clean_netflix_df.head(5)

,movie_title,director,cast,release_year,rating,duration,listed_in,description
0,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
1,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
2,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
3,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...
4,1920,Vikram Bhatt,"Rajneesh Duggal, Adah Sharma, Indraneil Sengup...",2008,TV-MA,143 min,"Horror Movies, International Movies, Thrillers",An architect and his wife move into a castle t...

In [21]:
#Connect to Local Database

rds_connection_string = "postgres:postgres@localhost:5432/ETL_project_movie_db"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [22]:
#Check for tables
engine.table_names()

['IMBD_data', 'netflix_data', 'imbd_data']

In [23]:
### Use pandas to load csv converted DataFrame into database
clean_netflix_df.to_sql(name='netflix_data', con=engine, if_exists='append', index=False)

In [24]:
##Confirm data has been added by querying the netflix_data table
pd.read_sql_query('select * from netflix_data', con=engine).head()

,movie_title,director,cast,release_year,rating,duration,listed_in,description
0,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
1,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
2,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
3,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...
4,1920,Vikram Bhatt,"Rajneesh Duggal, Adah Sharma, Indraneil Sengup...",2008,TV-MA,143 min,"Horror Movies, International Movies, Thrillers",An architect and his wife move into a castle t...

In [25]:
#See how many movies by release year

netflix_by_year = clean_netflix_df["release_year"].value_counts()
netflix_by_year.head()

2017    744
2016    642
2015    382
2014    244
2013    202
Name: release_year, dtype: int64

In [26]:
#See how many movies by Rating

netflix_by_year = clean_netflix_df["rating"].value_counts()
netflix_by_year.head()

TV-MA    997
TV-14    779
R        462
TV-PG    298
PG-13    275
Name: rating, dtype: int64