In [1]:
##Imports
from sqlalchemy import create_engine
import pandas as pd
from sqlalchemy import create_engine

In [2]:
##Store CSV into DataFrame

csv_file = "../Data/Netflix_titles.csv"
netflix_df = pd.read_csv(csv_file)
netflix_df.sample(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
3793,s5440,Movie,Scorpion King 5: Book of Souls,Don Michael Paul,"Zach McGowan, Pearl Thusi, Nathan Jones, Peter...",United States,23-Oct-18,2018,PG-13,102 min,"Action & Adventure, Sci-Fi & Fantasy",The Scorpion King joins forces with a Nubian p...
3051,s4385,Movie,Naga The Eternal Yogi,"Krishna Agazzi, Filippo Gastaldi",NaN,"Italy, India",5-Feb-17,2016,TV-PG,73 min,"Documentaries, International Movies",This documentary examines the naked yoga gurus...
4729,s6823,Movie,The Ring,Gore Verbinski,"Naomi Watts, Martin Henderson, David Dorfman, ...",United States,1-Jan-20,2002,PG-13,116 min,"Horror Movies, Thrillers",A reporter watches a video that supposedly set...
3637,s5241,Movie,Rocco,"Thierry Demaizière, Alban Teurlai",Rocco Siffredi,France,1-Sep-17,2016,TV-MA,103 min,"Documentaries, International Movies",Italian porn star Rocco Siffredi is showcased ...
999,s1381,Movie,ChuChuTV Surprise Eggs Learning Videos (English),NaN,NaN,NaN,18-Oct-19,2019,TV-Y,61 min,Children & Family Movies,From colors and letters to animals of all kind...

In [3]:
##Read Columns

for col in netflix_df.columns: 
    print(col)

show_id
type
title
director
cast
country
date_added
release_year
rating
duration
listed_in
description

In [4]:
##Drop all non-Movies and only capture U.S, and movies 2000-2017
netflix_df = netflix_df[(netflix_df.type == "Movie") & (netflix_df.release_year > 1999) & (netflix_df.release_year < 2018)] 
netflix_df.sample(10)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
3351,s4814,Movie,Peepli Live,"Anusha Rizvi, Mahmood Farooqui","Omkar Das Manikpuri, Raghuvir Yadav, Malaika S...",India,10-Jan-21,2010,TV-MA,109 min,"Comedies, Dramas, Independent Movies",Two indigent farmers consider suicide so that ...
499,s653,Movie,B.A. Pass,Ajay Bahl,"Shadab Kamal, Shilpa Shukla, Rajesh Sharma, Di...",India,7-Jun-18,2013,TV-14,99 min,"Dramas, Independent Movies, International Movies","Orphaned and at loose ends, young Mukesh falls..."
4583,s6617,Movie,The Lord of the Rings: The Return of the King,Peter Jackson,"Elijah Wood, Ian McKellen, Liv Tyler, Viggo Mo...","New Zealand, United States",1-Jan-20,2003,PG-13,201 min,"Action & Adventure, Sci-Fi & Fantasy",Aragorn is revealed as the heir to the ancient...
4941,s7128,Movie,Todo Sobre El Asado,"Mariano Cohn, Gastón Duprat",El Negro Álvarez,Argentina,1-Sep-17,2016,TV-MA,86 min,"Documentaries, International Movies",This quirky examination of Argentina's culture...
5119,s7409,Movie,Verses of Love 2,Guntur Soeharjanto,"Fedi Nuril, Tatjana Saphira, Dewi Sandra, Chel...",Indonesia,18-Oct-19,2017,TV-14,127 min,"Dramas, Faith & Spirituality, International Mo...","Now a lecturer in Edinburgh, Fahri tries to be..."
4697,s6776,Movie,The Prince,Brian A. Miller,"Jason Patric, Bruce Willis, John Cusack, Rain,...","United States, United Kingdom",22-Feb-19,2014,R,91 min,Action & Adventure,A former Mafia hit man living quietly as a mec...
3696,s5315,Movie,Russell Peters: Notorious,Dave Higby,Russell Peters,United States,14-Oct-13,2013,NR,72 min,Stand-Up Comedy,Global comedy star Russell Peters leaves no et...
2372,s3377,Movie,Kill Bill: Vol. 2,Quentin Tarantino,"Uma Thurman, David Carradine, Michael Madsen, ...",United States,1-Jan-20,2004,R,137 min,Action & Adventure,The Bride has three left on her rampage list: ...
3796,s5444,Movie,Scream 3,Wes Craven,"David Arquette, Neve Campbell, Courteney Cox, ...",United States,1-Jul-19,2000,R,117 min,Horror Movies,This installment of the tongue-in-cheek horror...
1509,s2160,Movie,Figures of Speech,Ari Levinson,Chris Pine,United States,21-Dec-16,2016,TV-PG,92 min,Documentaries,"In this documentary, passionate high schoolers..."

In [5]:
##Choose Columns

clean_netflix_df = netflix_df[['title', 'director', 'cast', 'release_year', 'rating', 'duration', 'listed_in', 'description']].copy()
clean_netflix_df = clean_netflix_df.rename(columns={'title': 'movie_title'})

clean_netflix_df = clean_netflix_df.reset_index(drop=True)
clean_netflix_df.head(5)

clean_netflix_df.to_csv("../Output/Netflix_clean.csv")

In [6]:
#Connect to Local Database

rds_connection_string = "postgres:postgres@localhost:5432/ETL_project_movie_db"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [7]:
#Check for tables
engine.table_names()

['IMBD_data', 'netflix_data', 'imbd_data']

In [8]:
### Use pandas to load csv converted DataFrame into database
clean_netflix_df.to_sql(name='netflix_data', con=engine, if_exists='append', index=False)

In [9]:
##Confirm data has been added by querying the netflix_data table
pd.read_sql_query('select * from netflix_data', con=engine).head()

,movie_title,director,cast,release_year,rating,duration,listed_in,description
0,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
1,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
2,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
3,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...
4,1920,Vikram Bhatt,"Rajneesh Duggal, Adah Sharma, Indraneil Sengup...",2008,TV-MA,143 min,"Horror Movies, International Movies, Thrillers",An architect and his wife move into a castle t...

In [10]:
#See how many movies by release year

netflix_by_year = clean_netflix_df["release_year"].value_counts()
netflix_by_year.head()

2017    744
2016    642
2015    382
2014    244
2013    202
Name: release_year, dtype: int64

In [11]:
#See how many movies by Rating

netflix_by_year = clean_netflix_df["rating"].value_counts()
netflix_by_year.head()

TV-MA    997
TV-14    779
R        462
TV-PG    298
PG-13    275
Name: rating, dtype: int64